### ISSUE TITLE
How to set up Java Development Environment to debug project without deployment the jar?

### ISSUE THREAD

**Issue by mingqin1** [awslabs/api-gateway-secure-pet-store#7]
Team:
  How do you develop the project prior to deploy the jar in Lambda console?
   I would like to set up a java maven project in IDE with proper configure in my local dev machine, I can debug the Lambda code which need accesses to DynamoDB and Cognito pool resources in AWS region.

  I am used to set up OpenVPN in my VPC to access the AWS resources.

**Comment by mingqin1** [comment]
I found this one:
http://docs.aws.amazon.com/AWSToolkitEclipse/latest/ug/lambda-tutorial.html

**Comment by sirfak** [comment]
Hi

Does compiled classes gets api key  (provided by profile credential providet) 
 embedded in them during compilation when java package is deployed as lamda function?

Thanks
Sirfak

**Comment by sapessi** [comment]
think you mean access key, not api key. AWS credentials in Lambda functions are assigned automatically based on the execution role. if your execution role is setup correctly then you can just initialize AWS client SDK classes in your code and they will pick up the correct credentials

**Comment by sirfak** [comment]
Yes access key.thanks alot
